#!/usr/bin/bash

word=$(cat /usr/share/dict/words | egrep "^[a-z]{6,8}$" | shuf -n 1)
word_count=${#word}
max_attempts=8
attempt=0
score=0

match=0
flag=0

read -p "Do you want to play this game?(y/n): " start

while [[ ! $start =~ ^(y|Y|yes|Yes|YES|n|no|No|NO)$ ]]
do
	read -p "Please enter y (play) or n (quit): " start		
done

while [[ $start =~ ^(y|Y|yes|Yes|YES)$ ]]
do
	echo $word
	for (( i=0; i<$word_count; i++ ))
	do
        	echo -n "_"
	done
	echo

	while [[ $attempt -lt $max_attempts && flag -eq 0 ]]
	do	
		read -p "Would you like to guess the word now (y/n)? " yesno
	
		if [[ $yesno =~ ^(y|Y|yes|Yes|YES)$ ]]
		then
			read -p "Guess the word!: " guess_word
			if [[ $guess_word == $word ]]
				then
				flag=1
				echo "You got the correct answer!"
				echo "The word was $word"
				echo "Your score: $((++score))"
				continue
			else
				echo "Your guess was wrong!"
				((attempt++))
				continue
			fi	
		fi 
	
		read -p "Attempt $(($attempt+1)): " guess_letter
		
		while [[ ! $guess_letter =~ ^[a-z]$ ]]
		do
			echo "You must enter one char letter!"
			read -p "Attempt $(($attempt+1)): " guess_letter
		done

		if [[ $guess_letters == *$guess_letter* ]]
        	then
	                echo "You already entered '$guess_letter'"
        		continue
		fi
		guess_letters+=$guess_letter	

		for(( c=0; c<$word_count; c++ ))
		do
			if [[ $guess_letters == *${word:$c:1}* ]]
				then echo -n ${word:$c:1}
				((match++))
				if [[ $match -eq $word_count ]]
					then
						flag=1
						echo "You got the correct answer!"
						echo "The word was $word!"
						echo "Your score: $((++score))"
				fi
			else 
				echo -n "_"
			fi
		done

		echo
		((attempt++))
		match=0
	done
	
	read -p "Do you want to play again?(y/n): " start
	word=$(cat /usr/share/dict/words | egrep "^[a-z]{6,8}$" | shuf -n 1)
	attempt=0
	flag=0
	guess_letters=""

done
