#!/usr/bin/bash

word=$(cat /usr/share/dict/words | egrep ^......?.?.?$ | shuf -n 1)
count=$(echo -n $word | wc -c)

echo $word
echo $count
i=0



for (( i=0; i<$count; i++ ))
do
	echo -n "_"
done

echo 
